### ISSUE TITLE
Error in Key mode + No key offset column

### ISSUE THREAD

**Issue by bascurtiz** [kokernutz/traktor-kontrol-screens#5] opened 2018-02-28 17:50 UTC
See: http://disq.us/p/1qbbdx5

Which version of Traktor do u use?

**Comment by bascurtiz** [comment] 2018-02-28 18:35
Downgraded from v2.11.2 11 to v2.11.1 31 & all works FYI :)

**Comment by skymakai** [comment] 2018-02-28 20:02
I'm on 2.11.2 11 with no issues seeing the Key Offset Column. (Mac)

**Comment by bascurtiz** [comment] 2018-02-28 22:46
Thanks Skymakai.
I updated thru Service Center installed Controller Editor 2.2.2 + Traktor 2.11.2 11 & errors are back using
this Screen hack.
Downgraded again to 2.11.1 131 & Screen hack works.
So defo an issue with Windows variant.
OS used: Win10 x64 [PC]
See examples: https://imgur.com/a/Uw1KN

**Comment by chronik78** [comment] 2018-03-10 08:40
I have similar issue using the latest Traktor version and the previous version on the latest Mac OSX. The beat to cue is small and in the browse screen I don't have key offset. Essentially it doesn't look as pictured. It look like a similar version to the ErikMinekus mod but with things not working. Thanks for your help.

**Comment by bascurtiz** [comment] 2018-03-10 10:53
@chronik78 
Does it look like this?
See examples: https://imgur.com/a/1WtXd

**Comment by kokernutz** [comment] 2018-03-10 20:46
After a hiatus, I've started working on these mods again. Here is the current state... I'll publish what I have tomorrow!

![img_7223](https://user-images.githubusercontent.com/757885/37246594-3627df26-247a-11e8-8b16-561c66240a25.jpg)

**Comment by bascurtiz** [comment] 2018-03-10 20:57
w00t!
I'll be your test-bunny =)

**Comment by chronik78** [comment] 2018-03-10 22:22
@bascurtiz yes looks exactly like that!

@kokernutz that would be awesome! From all the screens I've seen yours is the cleanest/most practical for the way I like to mix. Thanks for your efforts!

**Comment by kokernutz** [comment] 2018-03-11 15:33
Uh oh... am I going overboard?

![img_7226](https://user-images.githubusercontent.com/757885/37255236-ee233378-251f-11e8-9ac1-f23f79c4e727.jpg)

**Comment by bascurtiz** [comment] 2018-03-11 17:48
SYNC + LOCK + CURRENT KEY = Awesome add-ons!
These were a little hidden in previous built/Traktors built... though crucial info when altered!
If possible, CURRENT KEY bg-color based on the corresponding key color Traktor uses, see:
https://gyazo.com/5147e93a9775b26f768def7a66739d84

SYNC + LOCK color are already perfect.

BPM + PITCH = All good!
LOOP INDICATOR = Great change in size. Right color when active.
DECK INDICATOR = Great change in size. If possible, Blue when A or B, White when C or D.
BEAT COUNTER = Since its fairly big, why not make this outline + text gray instead of blue?

What are the 4 blocks underneath BEAT COUNTER for? To show off the ONE-beat in a bar?
If not, why not show the MASTER INDICATOR there?
Overall pic would be something like this:
https://imgur.com/a/y256m

**Comment by skymakai** [comment] 2018-03-11 17:51
I agree.
I like the layout of all the info in the header.  But, I'd prefer everything to be darker.  
Perhaps a colored outlines, but not filled color blocks.  I don't want a jumble of colored blocks in the corner of my decks, unless they're indicating Key Lock is turned on, or some other indicator I need to remember to turn off.

**Comment by kokernutz** [comment] 2018-03-11 18:24
The deck indicator (A, B, C, D) is color coded correctly. (blue/white)
The tempo and beat countdown is the same as the deck color. 

And I agree about it being too busy visually. I'll work on making it less offensive. :)

The idea with the blocks below the beat countdown was to indicate which beat in the bar you were on. The orange outline matches the MASTER track and the green interior shows sync-ed tracks. I wanted to do it this way because I was always checking the other screen to make sure I was starting the track at the exact moment I needed to, and that microsecond delay of moving my eyes made me unsure of myself.

![img_7229](https://user-images.githubusercontent.com/757885/37256887-46bda6aa-2537-11e8-9232-fc7b5b58a27a.jpg)
![img_7230](https://user-images.githubusercontent.com/757885/37256888-49ef8c6c-2537-11e8-9245-014d013f4ef9.jpg)

**Comment by skymakai** [comment] 2018-03-11 18:40
One reason I preferred your mod over the others is it's simplicity and similarity to the original.  Native Instruments left out some important stuff in their screens, and I'm grateful you're correcting that for me. 
As a seasoned DJ, there are only a few things I need to know quickly when looking at my Track deck header:  
Original Tempo/Tempo Offset
Sync/Master
Key Lock On/Off.

Most other things can be easily seen on the controller or otherwise:

Loop On/Off+Length shows up on the controller (on/off), in the waveform, and when changing the length.  I don't need it, though it doesn't take up much space in it's little circle.

Time Remaining is something I can tell by looking at the waveform and minute markers.

I put the Key in the Comments tag, so I already see that and don't need that.

I tend to use A/B for Track decks and C/D for Remix decks.  So, I can easily tell which is which and don't need to have an indicator of which deck it is..  Plus, there's the Deck switch button on the D2/S5/S8 to easily go between the two.

I can see the beat counter being helpful for people who are more visually inclined.  Personally, I use my ears and can easily tell what is a downbeat and what is an upbeat, and when a new bar starts.  I don't need it and would prefer a more simple layout.  Perhaps a fork of the project for Simple/Complex layouts would be good?  

What ever happened to 'user defined' preferences?  Is that even possible?

**Comment by bascurtiz** [comment] 2018-03-11 18:43
@skymakai 
I agree with the blocks filled with color.

@kokernutz 
How about this?
SYNC + LOCK + LOOP on: https://imgur.com/a/7xrnB
MASTER on + LOCK + LOOP off: https://imgur.com/a/iD2Jx

**Comment by kokernutz** [comment] 2018-03-11 19:53
@skymakai 
All good points and thank you for your enthusiasm! Yes, prefs are still something I want to implement... I just successfully created the first one for displaying album art in the deck header.

I'm thinking at this point I should definitely create a branch to keep with the original spirit of my mods. Do you want to create a mockup (it can be as simple as a doodle) and I'll create it? You probably only need to grab the screenshot I posted yesterday (in this thread) and let me know what I should change.

@bascurtiz 
This is what I did: 
![img_7234](https://user-images.githubusercontent.com/757885/37257804-1dd59a56-2544-11e8-8761-0566eb9d631b.jpg)

**Comment by bascurtiz** [comment] 2018-03-11 20:20
Looks good to me!
I’d Love to test it out.

**Comment by kokernutz** [comment] 2018-03-11 20:25
OK. I noticed the phase meter doesn't work when you've gone past your last cue point. Need to fix that.

Here you go...

[Screens.zip](https://github.com/kokernutz/traktor-kontrol-screens/files/1800839/Screens.zip)

**Comment by bascurtiz** [comment] 2018-03-11 21:12
@kokernutz 
Works great!
See: https://imgur.com/a/TfD9T

The beatphase is intelligent using that outline from the master, in the synced deck. Props.
Perhaps make the fontsize smaller of the title , artist & comment?

Also, not sure if it's possible or if u understood my earlier proposal:
The color coded key is showing.
But if I alter the key from let's say 4A to 2A, would be cool if that color would jump from Yellow (=4A) to Green (=2A).

**Comment by kokernutz** [comment] 2018-03-11 21:17
@bascurtiz 
Great. Yes, I need to figure out what I'm doing with that section over there. It's the section I'm least happy with. And I can confirm that bug... I need to detect the change and update the color.

How'd you get the FX display at the bottom?

**Comment by kokernutz** [comment] 2018-03-11 21:31
@bascurtiz 
Is that normal? I have an S5 and they slide down from the top when I touch the FX knobs... default S5 view:

![img_7239](https://user-images.githubusercontent.com/757885/37258710-0fe1d9a6-2552-11e8-81b5-7d99c84c4f88.jpg)

**Comment by bascurtiz** [comment] 2018-03-11 22:38
@kokernutz 
I think it's normal, since I can either change FX Bank 1 (on top) or FX Bank 2 (on bottom) on Left Deck, see pic where i'm touching a rotary knob on top + bottom at the same time:
https://imgur.com/a/5gold

Tested with Traktor 2.11.2 11:
Errors in keys are back.
No key showing in the deck-section + Err in Deck A+B in Browser section + Err in Key-mode change.
See: https://imgur.com/a/LPvoO

**Comment by chronik78** [comment] 2018-03-11 23:49
@kokernutz 
Looks great! I tested the new version above. The play screen appears as pictured however I am still having similar issues to before with the browsing screen which has error and doesn't show the key shift column. 
![20180312_101412](https://user-images.githubusercontent.com/37237631/37260071-0241cff4-25e3-11e8-85f5-eedf815308ad.jpg)

**Comment by kokernutz** [comment] 2018-03-11 23:50
@bascurtiz 
Interesting. The function convert Open Key to Camelot is returning an ERR so we at least know it is being called. Is this all tracks? And your files have something in the "Key" column in the browser? Can you post a pic of your PC's Traktor file browser with that column shown?

**Comment by kokernutz** [comment] 2018-03-11 23:51
@chronik78 
Are you on a PC running the latest version of Traktor? 2.11.2 64-bit?

**Comment by bascurtiz** [comment] 2018-03-12 00:02
@kokernutz 
This is on v2.11.1 31: https://gyazo.com/c9413b36151bd44971bef93d210044f3
That stuff doesnt change, with newer update I think, but I will update right now.

**Comment by kokernutz** [comment] 2018-03-12 00:08
@bascurtiz 
The only thing I can think of at the moment is an upper/lowercase matching problem. 

After you upgrade, and before you put the mods in place, can you find your **Keylock.qml** file and copy & paste this section into a new comment? (It's second from the bottom.) I'm curious if your **text:** field is different than mine.

```
  // key
  Text {
    anchors.top:              parent.top
    anchors.right:            parent.right
    anchors.topMargin:        67
    anchors.rightMargin:      20
    font.pixelSize:           fonts.largeFontSize
    font.family   :           "Pragmatica"
    font.capitalization: Font.AllUppercase
    color:                    colors.colorGrey104
    opacity: (keyDisplay.value=="") ? 0 : 1
    text:    "(" + keyDisplay.value + ((offset==0)?"":" ") + ")"
  }
```

**Comment by bascurtiz** [comment] 2018-03-12 00:14
@kokernutz 

  // key
  Text {
    anchors.top:              parent.top
    anchors.right:            parent.right
    anchors.topMargin:        67
    anchors.rightMargin:      20
    font.pixelSize:           fonts.largeFontSize
    font.family   :           "Pragmatica"
    font.capitalization: Font.AllUppercase
    color:                    colors.colorGrey104
    opacity: (keyDisplay.value=="") ? 0 : 1
    text:    "(" + keyDisplay.value + ((offset==0)?"":" ") + ")"
  }

**Comment by bascurtiz** [comment] 2018-03-12 00:17
@kokernutz 
Seems the same above, but check this out, the Key column is showing a different notation (without using your screenhack yet on the updated version):

https://gyazo.com/a8792d5ffa88952aceda3a81c348b5fd

**Comment by kokernutz** [comment] 2018-03-12 00:18
@bascurtiz 
Hmph, same as mine. I'm stabbing in the dark since I don't have a PC. Can you try these files?

[Screens.zip](https://github.com/kokernutz/traktor-kontrol-screens/files/1801037/Screens.zip)

**Comment by bascurtiz** [comment] 2018-03-12 00:24
@kokernutz 
Haven't tried the last built out u just posted, but that's it!
With new version it overwrites settings from Open Key to Musical.
https://gyazo.com/58aa4a8eaa29afaa16255a79f79e2c23

After setting it back to Open Key, it simply works again \o/

**Comment by kokernutz** [comment] 2018-03-12 00:25
@chronik78 
make sure your options are set correctly.

If it works I will close this issue!

**Comment by chronik78** [comment] 2018-03-12 05:44
@kokernutz I am using the latest version of Traktor and latest OSX. I changed the settings and this appears to have worked. Thanks guys! See below. Looks like this now. Is this right? I thought there was a column for key shift in an earlier version? Or was that removed? No biggie just curious.
![20180312_163620](https://user-images.githubusercontent.com/37237631/37267466-960cba4c-2614-11e8-8ce2-d7f6b7ec84f0.jpg)

**Comment by bascurtiz** [comment] 2018-03-12 11:29
@kokernutz 
@skymakai 
I've made a more clean look, based on the default screen of Traktor, but incorporated your add-ons.
I like it, since it takes less space + less jumble of colored blocks.
Also added Original Tempo. 
Check it out: https://imgur.com/a/Uviap

**Comment by kokernutz** [comment] 2018-03-12 12:05
@bascurtiz 
Looks good. I should be able to do that tonight. 

In the meantime, here is a new version where I tightened everything up and the key color changes when you adjust the key. Also, check the Prefs.qml file! Just three options right now: display cover art, display comment, and display phase meter. 

[Screens.zip](https://github.com/kokernutz/traktor-kontrol-screens/files/1802637/Screens.zip)

**Comment by bascurtiz** [comment] 2018-03-12 12:29
@kokernutz 
If you give me some clues, I can try to edit your QML files myself.

Tested new version:
- Color changing works as expected. Great!
- Prefs.qml is superhandy for those want adjust it to their likings. Awesome work.

**Comment by kokernutz** [comment] 2018-03-13 00:35
@skymakai 
@bascurtiz 

What do you think?

![img_7244](https://user-images.githubusercontent.com/757885/37316358-eb452966-2634-11e8-9e74-f928945c8e72.jpg)

**Comment by skymakai** [comment] 2018-03-13 00:43
Looks good; clean and simple.
How does it look without cover art?
And how does it look with comments?  
I'm concerned that comments may be truncated, as it looks like the title of the song is being truncated in your screenshot.  My typical comments can look like this:  `*** 8B/9B - [Groover][Chiller]`

**Comment by bascurtiz** [comment] 2018-03-13 00:51
@kokernutz 
Yep, if you can size down the Cover art a bit like in my example + change the fontsize of title + artist + comment a bit, you're there!
Though, I'd add the Original Tempo aswell, since that's important, as @skymakai already mentioned.
The B from deck B is easily replacable with the PNG that comes natively. Just size it down to 50%.
This way it's, all the values are not outlined in a filled colored box.
Keep it going, preferably taking my example in check!

**Comment by kokernutz** [comment] 2018-03-13 01:29
@skymakai 
@bascurtiz 

OK I made some changes so the max characters that are displayed for the artist/title/comment adapt to the presence of album art and the phase meter.

![img_7245](https://user-images.githubusercontent.com/757885/37317641-71082808-263c-11e8-99d5-51d72047d199.jpg)

**Comment by bascurtiz** [comment] 2018-03-13 01:31
@kokernutz 
Looks about right. Now I'm curious if Coverart + Phase meter are enabled.

**Comment by kokernutz** [comment] 2018-03-13 01:40
@bascurtiz 

![img_7246](https://user-images.githubusercontent.com/757885/37317905-df0938b4-263d-11e8-8cd0-c69a36eccd37.jpg)

**Comment by skymakai** [comment] 2018-03-13 01:55
Looking at that last picture, I get the idea that the Phase Meter should be on top.  It's size won't compete for space due to the Titles of songs being short.

**Comment by kokernutz** [comment] 2018-03-13 02:10
@skymakai 

On top of what? 

I was wondering if the phase meter could be squeezed in between the deck header and the waveform. Or overlayed on top of it without being distracting.

Do we need to see the key in the deck header? I was wondering if we could remove key, move key lock up, then slide the phase meter and master/sync indicator over to the right. Or I could combine lock/key into one slot. I could replace the "LOCK" text with a little padlock graphic or something similar to save space.

I shrunk the album art and deck header by 6 pixels to tighten things up a bit. I don't want to get any more compact than this because my eyes aren't that great and the LCDs on these things suck.

![img_7247](https://user-images.githubusercontent.com/757885/37318664-1e04db28-2642-11e8-97a4-c9ca3b249d0d.jpg)

**Comment by kokernutz** [comment] 2018-03-13 02:38
Anyway, here are the screens as they are right now. I may need to do fixing the artist/title/comment sizing for stems. (Will test those tomorrow.) And the phase meter still needs work. (It doesn't work after you passed the last cue point.)

[Screens.zip](https://github.com/kokernutz/traktor-kontrol-screens/files/1805241/Screens.zip)

**Comment by skymakai** [comment] 2018-03-13 02:54
Sorry I wasn't clear enough.
The phase meter is the widest element.  
So, it makes sense for it to be where the beat counter is at.  This is because there is more room to the right of the song Title; there is less room to the right of the Comments.

I like the idea of a symbol for Key Lock.  ErikMinekus, who did the Nexus and Prime mods, [shows the use of a Key Lock symbol in his Prime mod.  ](https://camo.githubusercontent.com/26da71779199cc1bb11f2701e3c6eb1d537c46ab/68747470733a2f2f4572696b4d696e656b75732e6769746875622e696f2f7472616b746f722d6b6f6e74726f6c2d73637265656e732f7072696d652f747261636b2d6465636b2e6a7067)

**Comment by skymakai** [comment] 2018-03-13 02:57
> And the phase meter still needs work. (It doesn't work after you passed the last cue point.)

This is because the phase meter counts down to the next Cue Point, right? 

If the playhead is past the last Cue Point, what other behavior would you have it do?

**Comment by kokernutz** [comment] 2018-03-14 00:22
@skymakai 
@bascurtiz 

This is what I have so far:

[Screens.zip](https://github.com/kokernutz/traktor-kontrol-screens/files/1809124/Screens.zip)

I found free svg of a padlock online. That way it can be scaled to any size without jaggies if I need to.

Where is original BPM going? Should it go where the master BPM is, so it is visible when you make the deck minimized? I feel like master/original BPM and tempo adjust (%) should all be grouped together logically. 

(Also, I removed outline mode for now. It was too difficult to juggle the placement of everything and making sure everything was aligned correctly with the outlines on and off.)

![img_7262](https://user-images.githubusercontent.com/757885/37376751-3649c8b4-26fc-11e8-9359-04c7fbd7e02a.jpg)

**Comment by bascurtiz** [comment] 2018-03-14 00:47
@kokernutz 
Oh, I didnt know u wanted the SVG instead;
Herby, check attachment.
[keylock-v2-svg.zip](https://github.com/kokernutz/traktor-kontrol-screens/files/1809158/keylock-v2-svg.zip)

If u want, I can make a svg of the native PNG of Deck A/B/C/D too.

Sure, Current BPM + Native BPM + Pitch should go all together row-to-row.
How about this?
See attach.
![master-screenhack-v3](https://user-images.githubusercontent.com/34075088/37377317-7f917422-2729-11e8-9f1c-61fe37cf1265.jpg)

And how is MASTER compared to sync eating up space in your last built?
Does it move the phasemeter to the left?

**Comment by skymakai** [comment] 2018-03-14 00:52
I really like bascurtiz layout!

I prefer the Key Lock icon bascurtiz uses.

I'd like the option to remove the Beat Counter and Phase Meter, as well as Album Artwork.

**Comment by kokernutz** [comment] 2018-03-14 00:58
@skymakai 
You can already remove album art and phase meter by editing the Prefs.qml file in the Screens/Views/Definitions folder. Just change "true" to "false".

I'll add an option for displaying/hiding beat countdown tomorrow.

@bascurtiz 
I'll make your changes tomorrow.

**Comment by skymakai** [comment] 2018-03-14 01:04
Much appreciated.  Please send me a paypal link so I can buy you a beer/coffee.

**Comment by bascurtiz** [comment] 2018-03-14 01:07
@kokernutz 
Awesome!
Attached the A, B, C & D native icons in SVG.
[screenhack-ABCD-svg.zip](https://github.com/kokernutz/traktor-kontrol-screens/files/1809217/screenhack-ABCD-svg.zip)

**Comment by kokernutz** [comment] 2018-03-14 11:50
@skymakai 
@bascurtiz 

Added pref to turn off beat countdown.
Updated lock icon.
Reverted track deck indicator back to original font.

Will work on orig BPM tonight.

Here's what it looks like with everything except track comment turned off:

![img_7265](https://user-images.githubusercontent.com/757885/37400729-338e3852-275c-11e8-8568-c8a0f994981a.jpg)

**Comment by bascurtiz** [comment] 2018-03-14 13:09
@kokernutz 
Great!

**Comment by bascurtiz** [comment] 2018-03-14 18:03
@kokernutz 
I perfected the size & shape of the Keylock icon, see pic + attachment.
![img_5062](https://user-images.githubusercontent.com/34075088/37421603-fd5ae25e-27b9-11e8-8a05-221f7e7eb09e.JPG)

[Lock_Icon-v2.zip](https://github.com/kokernutz/traktor-kontrol-screens/files/1812371/Lock_Icon-v2.zip)

**Comment by kokernutz** [comment] 2018-03-14 23:53
@skymakai 
@bascurtiz 

Presented without comment...

![img_7272](https://user-images.githubusercontent.com/757885/37437011-3e6e5300-27c1-11e8-87c7-285bd331f4b4.jpg)
![img_7273](https://user-images.githubusercontent.com/757885/37437012-407c3ae0-27c1-11e8-9be0-17f040428b66.jpg)

**Comment by bascurtiz** [comment] 2018-03-15 00:14
@kokernutz 
I like it!
Good choice bringing the PHASE METER below the BEAT COUNTDOWN.
Just to make it more distinguished what is what,
perhaps make the PITCH + ORIGINAL BPM a different color than the CURRENT BPM?
Like the same Blue as been used for TITLE + COMMENT?

**Comment by kokernutz** [comment] 2018-03-15 00:18
@bascurtiz 

Good call: 

![img_7275](https://user-images.githubusercontent.com/757885/37437652-c0dfee18-27c4-11e8-877d-405754c20679.jpg)

**Comment by bascurtiz** [comment] 2018-03-15 00:21
Yep, more streamlined this way.
Love to test it out!

**Comment by kokernutz** [comment] 2018-03-15 00:23
@bascurtiz 

Here you go.

[Screens.zip](https://github.com/kokernutz/traktor-kontrol-screens/files/1813576/Screens.zip)

**Comment by skymakai** [comment] 2018-03-15 00:48
Seems like @bascurtiz Key Lock icon might be a better fit, no?

**Comment by kokernutz** [comment] 2018-03-15 00:50
@skymakai 

I am using it. The pixel density of the screens is poor. That's the best that I can do. (Plus, his screenshot is actually a Photoshop mockup if I'm not mistaken.)

**Comment by skymakai** [comment] 2018-03-15 00:52
One last thing... 

Can a user defined option for colored waveform easily implemented?

**Comment by kokernutz** [comment] 2018-03-15 00:53
@skymakai 

Yes! You mean Spectrum or something else? It was on my list of things to do.

**Comment by skymakai** [comment] 2018-03-15 00:56
Yes, the Spectrum waveform, as well as the song overview below.

**Comment by kokernutz** [comment] 2018-03-15 01:07
@skymakai 

Something like this? :) 

I need to figure out what the RGB values are that Traktor is using for Spectrum. And too be honest, I think the way the waveforms are generated for the D2/S5/S8 is different than the desktop app. I say that because sometimes the waveform is distinctly different on the controller where you see characteristics on your computer that you can't see on the controller or vice versa. So I'm not sure I'm going to get a perfect match for that.

![img_7278](https://user-images.githubusercontent.com/757885/37438901-ad88534e-27cb-11e8-803a-a7133d6526dc.jpg)

**Comment by skymakai** [comment] 2018-03-15 01:56
Yes, like that. 

I’m aware that the color scheme can’t match the Desktop app.

**Comment by kokernutz** [comment] 2018-03-15 02:12
@skymakai 

OK, give it a whirl:

[Screens.zip](https://github.com/kokernutz/traktor-kontrol-screens/files/1813773/Screens.zip)

**Comment by bascurtiz** [comment] 2018-03-15 03:33
@kokernutz 
It wasn't a mockup in PS, but simply replaced your icon with mine.
In your later builts from that point, it simply doesnt work as shown in the previous pic.
Anywho, I've did a re-edit that comes close and is a better fit (smaller mainly).
See pic + attach.
![img_5073](https://user-images.githubusercontent.com/34075088/37443028-ccbaa760-2809-11e8-83c2-17241dd4a22e.JPG)
[Lock_Icon-v3.zip](https://github.com/kokernutz/traktor-kontrol-screens/files/1813911/Lock_Icon-v3.zip)

**Comment by skymakai** [comment] 2018-03-15 04:22
About to try it out.  Where is the user preferences file?

**Comment by skymakai** [comment] 2018-03-15 04:31
Just tried it out.  I love it.  

One question:  
Is it possible to add functionality to the buttons to the left of the screens?  

There is the 'gear' button, two 'box' buttons, and an 'arrow' button.  The bottom box button has no function when holding Shift.  I'd like to know if holding Shift and pressing that bottom box button could activate/deactivate Key Lock.

**Comment by kokernutz** [comment] 2018-03-15 12:08
@skymakai 

Challenge accepted. I can make new key mappings, but I can't yet figure out how to enable/disable keylock. I can assign that button to key lock reset, but that doesn't enable/disable it. Might take some digging as it is not obvious in the code how they are doing it. (I see the references to reset/coarse/fine adjustments but not toggling it off and on.)

**Comment by bascurtiz** [comment] 2018-03-15 15:42
@kokernutz 
Got the same expected size & shape back using Lock_Icon-v2, but altered your code.
Icon used: https://github.com/kokernutz/traktor-kontrol-screens/files/1812371/Lock_Icon-v2.zip
RL Pic:
![img_5074](https://user-images.githubusercontent.com/34075088/37473853-54ea5e9a-286f-11e8-94d8-6161a9d50d3a.JPG)

Changed code in DeckHeader.qml at Key-section from:
`width:  fieldHeight + 3
 height: fieldHeight + 4
`
to:
`    width:  fieldHeight
    height: fieldHeight
`

**Comment by kokernutz** [comment] 2018-03-16 02:01
@skymakai 
I still don't know how to toggle keylock programmatically. So I will come back to remapping that key later.

In the meantime I think you asked for the ability to shut off time remaining, so I created a pref for that.

![img_7285](https://user-images.githubusercontent.com/757885/37499799-260841b4-289c-11e8-9567-45e5db05c9fc.jpg)

I also fixed a bug in the browser where the matching indicator would not change if the master track changed. (From another controller or your Mac/PC.) Now the key matching values are recalculated.

Here are the files: 

[Screens.zip](https://github.com/kokernutz/traktor-kontrol-screens/files/1817688/Screens.zip)

I think that's my release candidate. I want to clean up some of the deck header code because my naming conventions are terrible. But I expect to release on Monday. Please report any findings! And a huge thanks for your feedback and help!

**Comment by kokernutz** [comment] 2018-03-19 11:40
The update has been released!

**Closed by kokernutz** 2018-03-19 11:40 UTC

**Comment by skymakai** [comment] 2018-03-19 19:04
Were there any changes since you last linked the download for the Screens folder?

**Comment by kokernutz** [comment] 2018-03-19 20:49
@skymakai some code cleanup and I put a white line above the c & d deck when they are small/medium sized. I’d keep what you have if you are happy.
